#:schema node_modules/wrangler/config-schema.json
name = "controlled-recursive-do"
main = "main.ts"
compatibility_date = "2025-01-09"

[durable_objects]
bindings = [
  { name = "RECURSIVE_FETCHER", class_name = "RecursiveFetcherDO" }
]

[[migrations]]
tag = "v1"
new_classes = ["RecursiveFetcherDO"]
