#:schema node_modules/wrangler/config-schema.json
name = "recursive-do"
main = "worker.ts"
compatibility_date = "2025-01-09"

# Durable Object declarations
[[durable_objects.bindings]]
name = "RATE_LIMITER"
class_name = "RequestSchedulerDO"

[[durable_objects.bindings]]
name = "CREATOR"
class_name = "CreatorDO"

# Migrations for Durable Objects
[[migrations]]
tag = "v1" # version tag for this migration
new_classes = ["RequestSchedulerDO", "CreatorDO"]